parabank:
  environment.name: PARABANK-UAT
  environment.type: UAT
  uat.url: https://parabank.parasoft.com/parabank/index.htm
  dashboard.endpoint: /overview.htm
  browser: safari

tool-shop:
  environment.name: TOOL-SHOP
  environment.type: UAT
  uat.url: https://practicesoftwaretesting.com/
  browser: edge


