runtime.resources.dir=../Framework/src/main/resources/runtimeResources
screenshot.dir=target/screenshots/
reports.dir=target/HTML_Reports/
drivers.dir=../supportData/drivers
files.dir=../supportData/Files/txtFiles